Application/OnlineDiagnosticSystem/OnlineDiagnosticSystem/Controllers/AccountTypeTablesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DatabaseLayer;

namespace OnlineDiagnosticSystem.Controllers
{
    public class AccountTypeTablesController : Controller
    {
        private OnlineDiagnosticLabSystemDbEntities db = new OnlineDiagnosticLabSystemDbEntities();

        // GET: AccountTypeTables
        public ActionResult Index()
        {
            if (String.IsNullOrEmpty(Convert.ToString(Session["Username"])))
            {
                return RedirectToAction("Login", "Home");
            }
            return View(db.AccountTypeTables.ToList());
        }

        // GET: AccountTypeTables/Details/5
        public ActionResult Details(int? id)
        {
            if (String.IsNullOrEmpty(Convert.ToString(Session["Username"])))
            {
                return RedirectToAction("Login", "Home");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AccountTypeTable accountTypeTable = db.AccountTypeTables.Find(id);
            if (accountTypeTable == null)
            {
                return HttpNotFound();
            }
            return View(accountTypeTable);
        }

        // GET: AccountTypeTables/Create
        public ActionResult Create()
        {
            if (String.IsNullOrEmpty(Convert.ToString(Session["Username"])))
            {
                return RedirectToAction("Login", "Home");
            }
            return View();
        }

        // POST: AccountTypeTables/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AccountTypeID,Name")] AccountTypeTable accountTypeTable)
        {
            if (String.IsNullOrEmpty(Convert.ToString(Session["Username"])))
            {
                return RedirectToAction("Login", "Home");
            }
            if (ModelState.IsValid)
            {
                db.AccountTypeTables.Add(accountTypeTable);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(accountTypeTable);
        }

        // GET: AccountTypeTables/Edit/5
        public ActionResult Edit(int? id)
        {
            if (String.IsNullOrEmpty(Convert.ToString(Session["Username"])))
            {
                return RedirectToAction("Login", "Home");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AccountTypeTable accountTypeTable = db.AccountTypeTables.Find(id);
            if (accountTypeTable == null)
            {
                return HttpNotFound();
            }
            return View(accountTypeTable);
        }

        // POST: AccountTypeTables/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AccountTypeID,Name")] AccountTypeTable accountTypeTable)
        {
            if (String.IsNullOrEmpty(Convert.ToString(Session["Username"])))
            {
                return RedirectToAction("Login", "Home");
            }
            if (ModelState.IsValid)
            {
                db.Entry(accountTypeTable).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(accountTypeTable);
        }

        // GET: AccountTypeTables/Delete/5
        public ActionResult Delete(int? id)
        {
            if (String.IsNullOrEmpty(Convert.ToString(Session["Username"])))
            {
                return RedirectToAction("Login", "Home");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AccountTypeTable accountTypeTable = db.AccountTypeTables.Find(id);
            if (accountTypeTable == null)
            {
                return HttpNotFound();
            }
            return View(accountTypeTable);
        }

        // POST: AccountTypeTables/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (String.IsNullOrEmpty(Convert.ToString(Session["Username"])))
            {
                return RedirectToAction("Login", "Home");
            }
            AccountTypeTable accountTypeTable = db.AccountTypeTables.Find(id);
            db.AccountTypeTables.Remove(accountTypeTable);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Application/OnlineDiagnosticSystem/OnlineDiagnosticSystem/Views/AccountTypeTables/Create.cshtml
@model DatabaseLayer.AccountTypeTable

@{
    ViewBag.Title = "Account Type";
}

<h4>Add</h4>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>AccountTypes</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name,"Enter Account Type", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="genric-btn primary" />
                @Html.ActionLink("Back to List", "Index", null, new { @class = "genric-btn default" })
            </div>
        </div>
    </div>
}

Application/OnlineDiagnosticSystem/OnlineDiagnosticSystem/Views/AccountTypeTables/Delete.cshtml
@model DatabaseLayer.AccountTypeTable

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AccountTypeTable</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Application/OnlineDiagnosticSystem/OnlineDiagnosticSystem/Views/AccountTypeTables/Details.cshtml
@model DatabaseLayer.AccountTypeTable

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>AccountTypeTable</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.AccountTypeID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Application/OnlineDiagnosticSystem/OnlineDiagnosticSystem/Views/AccountTypeTables/Edit.cshtml
@model DatabaseLayer.AccountTypeTable

@{
    ViewBag.Title = "Edit";
}

<h4>Edit</h4>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h5>Account Type</h5>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.AccountTypeID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="genric-btn success" />
                @Html.ActionLink("Back to List", "Index", null, new { @class = "genric-btn default" })
            </div>
        </div>
    </div>
}

Application/OnlineDiagnosticSystem/OnlineDiagnosticSystem/Views/AccountTypeTables/Index.cshtml
@model IEnumerable<DatabaseLayer.AccountTypeTable>

@{
    ViewBag.Title = "Account Types";

}

<h2>Account Types</h2>
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<div class="w3-clear w3-center nextprev">
    
        @Html.ActionLink("Add Account Type", "Create", "AccountTypeTables", new { @style = "float:inline-end;", @class = "generic-btn primary" })
    </div>
    <br>
    <div class="w3-clear w3-center nextprev">
        <input type="text" id="searchtype" name="searchtype" class="form-control col-md-3" style="float:right;" placeholder="search here" />
        <br>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-hover" id="dataTable" width="100%" cellspacing="10">
                    <thead>
                        <tr>
                            <th>
                                Account Type
                            </th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody id="searchvalue">
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Name)
                                </td>
                                <td>
                                    @Html.ActionLink("Edit", "Edit", new { id = item.AccountTypeID }, new { @class = "generic-btn success" })
                                </td>
                            </tr>
                        }
                    </tbody>

                </table>
            </div>
        </div>
    </div>

    <script type="text/javascript">
        $(document).ready(function () {
            $("#searchtype").on("keyup", function () {
                var value = $(this).val().toLowerCase();
                $("#searchvalue tr").filter(function () {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });

    </script>